### ISSUE TITLE
No match displayed in minimap if not in the marker layer

### ISSUE THREAD

**Issue by abe33** [atom-minimap/minimap-find-and-replace#14]
In latest version of find-and-replace, when running on master with marker layers enabled, no decorations are displayed if there's no match in the the visible part of the marker layer.

We'll need to find a way to get these match directly from find-and-replace.

**Comment by abe33** [comment]
@fundon While I'm working on the es6 conversion, could you take a look at this to see if we have a easy way to workaround the recent changes in find-and-replace?

**Comment by fundon** [comment]
Ok, I'll look at this and follow you. :)

**Comment by abe33** [comment]
So, for a pointer, the solution seems to watch if the find-and-replace find model has a property named `resultsresultsMarkerLayer` and then change the logic to use that layer rather than relying on the text editor methods.

Note that the layer is unique so there might be some cleanup to do when switching the active editor.

**Comment by fundon** [comment]
Okay, thank your for your reminding.

**Comment by abe33** [comment]
I think you didn't get what I was talking about :sweat_smile:. 
I wasn't talking about converting this package to ES6 (even if it'll be the case one day), but rather to fix the issue with beta/master. Actually the use of a marker layer prevents the plugin to retrieve the markers properly.

**Comment by fundon** [comment]
😂 , Now, I got it!!!

**Comment by fundon** [comment]
@abe33 this? https://discuss.atom.io/t/problem-with-findmarkers-function-of-texteditor/23416/14

**Comment by fundon** [comment]
I left too long. Need time to familiar with the APIs.  😬

**Comment by abe33** [comment]
Yes, that's a part of the problem, but hopefully nathan made some change to find-and-replace to expose a service for us: https://github.com/atom/find-and-replace/pull/614

The best course of action is to wait for this PR to be merged and released so that what we just have to deal with two use cases: 

1. There's no service, so we use the current strategy (for legacy version of Atom)
2. There's a service, so we use the service to get the results marker layer instead of accessing directly the text editor

**Comment by fundon** [comment]
Okay, I wait it.

**Comment by abe33** [comment]
The change was quite simple after all, and both version are supported with almost no change in the binding object.

I'll publish the patch tomorrow

**Comment by fundon** [comment]
Nice
