### ISSUE TITLE
Minimap 

### ISSUE THREAD

**Issue by napocon2402** [atom-minimap/minimap-find-and-replace#15]
I am spanish, so i can't write really good in english, im a begginer in writting code I install the package of minimap and i cant see in the code. sombody can help me?

**Comment by abe33** [comment]
Did you install the `minimap` package along with `minimap-find-and-replace`? This package is just a plugin for the main `minimap` package.

**Comment by napocon2402** [comment]
Ohh thank you! I'm stupid
