### ISSUE TITLE
3 User Friendly Suggestions (all from TextMate)

### ISSUE THREAD

**Issue by EnterpriseBranding** [atom-minimap/minimap-find-and-replace#17]
1. It would be awesome to have a find and replace similar to TextMate where the find value return all the found items in a glance type view. Then clicking any of those highlighted items takes a user to that line. 
   -- See screenshot @ http://take.ms/dzvSb
2. It would also be good to see in that glance type view to see the results of the replace value before sending the replace action. 
   -- See screenshot @ http://take.ms/UYMB0
3. It would be good, if available to have the find and replace pop out, as in an external window. 

Just suggestions : ) 

Thoughts?

**Comment by abe33** [comment]
Shouldn't you post these suggestions on the `find-and-replace` package directly? This package is just responsible for displaying the search results in the minimap.
