### ISSUE TITLE
Tempory disable Syntax highlight when "find and replace" is enabled.

### ISSUE THREAD

**Issue by yufanyufan** [atom-minimap/minimap-find-and-replace#19]
The colorful "Syntax highlight" makes it impossible to spot the highlight from "find and replace".

**Comment by UziTech** [comment]
PRs are welcome 😁

**Comment by UziTech** [comment]
I'm going to close this in favor of [customization](https://github.com/atom-minimap/minimap-find-and-replace#customization)
