### ISSUE TITLE
Markers present on minimap after closing search dialog in a different tab

### ISSUE THREAD

**Issue by krzysztof-sikorski** [atom-minimap/minimap-find-and-replace#21]
There is a bug on recent version of Atom, minimap or this package. Seems to be a communication problem between packages so I am not sure on which repository it should be reported, but this package seems (at first glance) to be the most probable culprit, so I decided to report it here.

**Steps to reproduce:**

- open more than one tab
- open "find in buffer" dialog in a tab and search for a string that can be found, search results are marked on minimap
- switch to a different tab
- close "find in buffer" dialog (seems to not matter if you close via ESC key or via menu option)
- switch back to original tab: search results are still marked on minimap, they disappear if you open the dialog again and search for anything

**Software versions:**

- Atom: 1.15.0
- minimap: 4.26.8
- minimap-find-and-replace: 4.5.2

**Comment by krzysztof-sikorski** [comment]
Update: to hide erroneous markers, it seems to be enough to just open and close search dialog.

**Comment by collinjackson93** [comment]
I have experienced the same problem. To add to this, if you search in tab 1, close the find/replace dialog from tab 1 (be sure to leave the search term in the search bar), switch to tab 2, then switch back to tab 1, the term will reappear as highlighted in the minimap.

**Comment by abe33** [comment]
Hi there, yeah it's a troublesome issue, I'll need to find some time to work on it. Stay tuned.

**Comment by krzysztof-sikorski** [comment]
Update: I cannot reproduce the bug after updating `minimap` to the latest version (4.27.1).

**Comment by krzysztof-sikorski** [comment]
Damn, I was too hasty with closing. I just encountered the bug again :disappointed:

**Comment by borishere** [comment]
The bug is still there!

**Comment by sompylasar** [comment]
The highlight re-appears after closing the "find in buffer" dialog and switching tabs away from the one where minimap is active and back to it, without re-opening the "find in buffer" dialog. So it's not just about removing the highlight when closing the dialog, but about **not restoring** the highlight if the "find in buffer" is not currently open.

**Comment by UziTech** [comment]
this might be fixed in #24
