### ISSUE TITLE
The found word does not disappear if find-and-replace pane is closed from another editor

### ISSUE THREAD

**Issue by aminya** [atom-minimap/minimap-find-and-replace#35]
When you search for a word, and then change to another editor and return back close the find-replace pane, the words are still shown as highlighted

![find-replace](https://user-images.githubusercontent.com/16418197/101383123-5a7b5900-387e-11eb-8fae-b31d03950876.gif)

**Comment by UziTech** [comment]
I can't seem to reproduce this. Can you post a gif of it happening?

**Comment by aminya** [comment]
![find-replace](https://user-images.githubusercontent.com/16418197/101383123-5a7b5900-387e-11eb-8fae-b31d03950876.gif)
