### ISSUE TITLE
Find-and-replace won't activate

### ISSUE THREAD

**Issue by shazaldinho4** [atom-minimap/minimap-find-and-replace#50]
Find and replace plugin won't activate. I've toggled everything on and off, reinstalled both minimap and find and replace but it won't work. Minimap package works fine.

**Comment by UziTech** [comment]
After updating minimap I can reproduce this. @aminya is this because of something that changed in minimap?

**Comment by UziTech** [comment]
I could preproduce this but After restarting Atom it seems to work fine 🤷‍♂️. Maybe an intermittent bug?

@shazaldinho4 does it still happen for you after restarting Atom?

**Comment by UziTech** [comment]
And can you give more information like:

- Atom version
- OS version
- minimap version

**Comment by shazaldinho4** [comment]
Still happens after a restart, unfortunately. I'm using atom version 1.54.0, macOS 11.1 and minimap 4.38.3.

**Comment by aminya** [comment]
@UziTech Nothing has changed. I will investigate this.

**Comment by aminya** [comment]
@shazaldinho4 Try redownloading the package. Sometimes the connection issues result in a partial download.

**Comment by aminya** [comment]
I think this is fixed.

**Comment by UziTech** [comment]
@shazaldinho4 if this is still an issue feel free to reopen it with more information

**Comment by Z-Zen** [comment]
Hi,

Sorry for re-opening this issue. I recently started using `Atom`.

I have installed both packages `minimap` and the `minimap-find-and-replace`.

`minimap` is loading fine, however, `minimap-find-and-replace` isn't.

Atom: `1.55.0 x64`
Electron: `6.1.12`
OS: `Windows 10`
minimap-find-and-replace version: `v5.0.8`

Hitting `CTRL` + `F` shows the usual `find` bar:

![image](https://user-images.githubusercontent.com/19333943/114383252-a708d500-9b8d-11eb-9ffd-dd2a5d1aee75.png)

and `minimap` shows its activated:

![image](https://user-images.githubusercontent.com/19333943/114383391-c56ed080-9b8d-11eb-9d34-5a9d449b2bed.png)

Am I missing something ?

If you need any more information, please let me know.

**Comment by UziTech** [comment]
@Z-Zen What happens when you start typing in the find bar? does it highlight the search results in the minimap? Could you try changing the color to see if it is just something that you can't see?

Try adding the following to your atom style sheet:

```css
.minimap .search-result {
  background: yellow;
}
```

**Comment by Z-Zen** [comment]
Thanks for the quick reply!

> @Z-Zen What happens when you start typing in the find bar? does it highlight the search results in the minimap? Could you try changing the color to see if it is just something that you can't see?

Yes it does, here I started typing the few numbers of the first line and it lit on the minimap.
![image](https://user-images.githubusercontent.com/19333943/114537780-e3523900-9c52-11eb-875a-32711847a167.png)

> Try adding the following to your atom style sheet:
> 
> ```css
> .minimap .search-result {
>   background: yellow;
> }
> ```
I added it as you have seen below. But the buttons of `Find Prev` and other buttons are not showing!

![image](https://user-images.githubusercontent.com/19333943/114538019-2f04e280-9c53-11eb-8bfe-7f6d7c6b9506.png)

**Comment by UziTech** [comment]
All this package does is highlights the search results in minimap. It doesn't add any buttons to anything.
