### ISSUE TITLE
Breaks ⌘+D, ⌘+F behaviour

### ISSUE THREAD

**Issue by yaroshevych** [atom-minimap/minimap-find-and-replace#6]
By default, when you select a word with ⌘+D, and then invoke search with ⌘+F, selected word is used in the search. When ```minimap-find-and-replace``` package is installed, it's not working after second attempt.

Steps to reproduce:
 1. select a word with ⌘+D
 1. invoke search with ⌘+F
 1. selected word is used in the search
 1. select another word with ⌘+D
 1. invoke search with ⌘+F
 1. previous word is used in the search

Atom 0.189.0 on OSX Yosemite.

**Comment by abe33** [comment]
Thanks for the report, 

I can reproduce it, but I have no idea at that point why this package would affect the `find-and-replace` package. I'll take time investigate it later this week.
